import { colors } from '../../theme/colors';
import { layout } from '../../theme/layout';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    ...layout.content,
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 48,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 12,
  },
  exitButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitText: { fontSize: 16, color: colors.accent },
  title: { fontSize: 20, fontWeight: '700', color: colors.text },
  placeholder: { width: 36 },
  livesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    marginBottom: 8,
    gap: 4,
  },
  livesLabel: { fontSize: 15, color: colors.muted, fontWeight: '600' },
  heart: { fontSize: 20 },
  progressText: {
    marginLeft: 'auto',
    fontSize: 13,
    color: colors.accent,
    fontWeight: '600',
  },
  instruction: {
    fontSize: 13,
    color: colors.muted,
    paddingHorizontal: 20,
    marginBottom: 16,
    lineHeight: 18,
  },
  feedbackToast: {
    alignSelf: 'center',
    backgroundColor: colors.surface,
    paddingHorizontal: 16,
    paddingVertical: 6,
    borderRadius: 20,
    marginBottom: 8,
  },
  feedbackToastText: { color: '#FFF', fontSize: 13, fontWeight: '600' },
  paragraphContainer: { paddingHorizontal: 20, paddingBottom: 24 },
  wordsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  wordChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1.5,
    borderColor: colors.border,
    borderTopColor: 'rgba(255, 255, 255, 0.28)',
    backgroundColor: colors.surface,
  },
  word_default: { borderColor: colors.border,
    borderTopColor: 'rgba(255, 255, 255, 0.28)', backgroundColor: colors.surface },
  word_caught: { borderColor: '#22C55E', backgroundColor: colors.surfaceRaised },
  word_wrong: { borderColor: '#EF4444', backgroundColor: colors.surfaceRaised },
  word_missed: { borderColor: '#F97316', backgroundColor: colors.surfaceRaised },
  wordText: { fontSize: 15, color: colors.text },
  wordText_default: { color: colors.text },
  wordText_caught: { color: '#86EFAC', fontWeight: '600' },
  wordText_wrong: { color: '#FCA5A5', fontWeight: '600' },
  wordText_missed: { color: '#FDBA74', fontWeight: '600' },
  banner: {
    margin: 20,
    padding: 16,
    borderRadius: 16,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
  },
  bannerWin: { backgroundColor: colors.surfaceRaised },
  bannerText: { fontSize: 18, fontWeight: '700', color: colors.text },
  bannerSub: { fontSize: 13, color: colors.muted, marginTop: 4 },
} as any);
