import { colors } from '../../theme/colors';
import { layout } from '../../theme/layout';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    ...layout.content,
    flex: 1,
    backgroundColor: colors.background,
    paddingTop: 48,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    marginBottom: 8,
  },
  exitButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
  },
  exitText: { fontSize: 16, color: colors.accent },
  title: { fontSize: 20, fontWeight: '700', color: colors.text },
  timerBadge: {
    borderWidth: 2,
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  timerText: { fontSize: 14, fontWeight: '700' },
  storyTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.accent,
    paddingHorizontal: 20,
    marginBottom: 4,
  },
  instruction: {
    fontSize: 12,
    color: colors.muted,
    paddingHorizontal: 20,
    marginBottom: 12,
    lineHeight: 17,
  },
  sentencesContainer: {
    paddingHorizontal: 20,
    paddingBottom: 100,
    gap: 10,
  },
  sentenceCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 12,
    borderWidth: 1.5,
    borderColor: '#E0E7FF',
    gap: 10,
  },
  sentenceSelected: { borderColor: colors.accent, backgroundColor: colors.surface },
  sentenceCorrect: { borderColor: '#22C55E', backgroundColor: colors.surfaceRaised },
  sentenceWrong: { borderColor: '#EF4444', backgroundColor: colors.surfaceRaised },
  indexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: colors.surfaceRaised,
    alignItems: 'center',
    justifyContent: 'center',
  },
  indexBadgeSelected: { backgroundColor: colors.accent },
  indexBadgeCorrect: { backgroundColor: '#22C55E' },
  indexBadgeWrong: { backgroundColor: '#EF4444' },
  indexText: { fontSize: 13, fontWeight: '700', color: '#FFF' },
  sentenceText: { flex: 1, fontSize: 14, color: colors.text, lineHeight: 20 },
  sentenceTextSelected: { color: colors.accent, fontWeight: '600' },
  selectedIcon: { fontSize: 16 },
  resultIcon: { fontSize: 16 },
  footer: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    right: 20,
  },
  submitButton: {
    backgroundColor: colors.accent,
    paddingVertical: 14,
    borderRadius: 14,
    alignItems: 'center',
  },
  submitButtonText: { color: '#FFF', fontSize: 16, fontWeight: '700' },
  resultBanner: {
    position: 'absolute',
    bottom: 24,
    left: 20,
    right: 20,
    borderRadius: 14,
    padding: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  resultBannerWin: { backgroundColor: colors.surfaceRaised },
  resultBannerLose: { backgroundColor: colors.surfaceRaised },
  resultBannerText: { fontSize: 15, fontWeight: '700', color: colors.text },
  resultBannerScore: { fontSize: 20, fontWeight: '800', color: colors.text },
});
