import { colors } from '../../theme/colors';
import { layout } from '../../theme/layout';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  textColor: { color: '#22c55e' },
  textColor2: { color: '#ef4444' },
  safeArea: {
    ...layout.content,
    flex: 1,
    backgroundColor: colors.background,
  },

  // ── Intro ──
  introContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 20,
  },
  introIconWrap: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: '#3b82f6',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  introIcon: { fontSize: 44 },
  introTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#f1f5f9',
    letterSpacing: -0.5,
  },
  introSubtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 4,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  introDivider: {
    width: 48,
    height: 3,
    backgroundColor: '#3b82f6',
    borderRadius: 2,
    marginVertical: 20,
  },
  introDescription: {
    fontSize: 16,
    color: colors.muted,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  introHighlight: { color: '#f59e0b', fontWeight: '700' },
  introRules: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    gap: 14,
    marginBottom: 28,
  },
  ruleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  ruleEmoji: { fontSize: 20, width: 28 },
  ruleText: {
    flex: 1,
    fontSize: 14,
    color: '#cbd5e1',
    lineHeight: 20,
    fontWeight: '500',
  },
  startButton: {
    width: '100%',
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 12,
    elevation: 8,
  },
  startButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  backLink: { marginTop: 16, padding: 8 },
  backLinkText: { color: colors.muted, fontSize: 14, fontWeight: '600' },

  // ── Game Header ──
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 8,
  },
  topicLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  topicName: {
    fontSize: 18,
    color: '#f1f5f9',
    fontWeight: '800',
    marginTop: 2,
  },
  counterBadge: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: '#334155',
  },
  counterText: {
    fontSize: 15,
    fontWeight: '800',
    color: '#f59e0b',
  },

  // ── Progress Dots ──
  dotsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    paddingHorizontal: 18,
    gap: 6,
    marginBottom: 16,
  },
  dot: {
    width: 10,
    height: 10,
    borderRadius: 5,
  },
  dotActive: {
    backgroundColor: '#3b82f6',
    width: 24,
    borderRadius: 5,
  },

  // ── Sentence area ──
  sentenceWrapper: {
    flex: 1,
    paddingHorizontal: 18,
    gap: 14,
  },
  questionLabel: {
    fontSize: 13,
    color: colors.muted,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.8,
  },
  sentenceCard: {
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 22,
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  sentenceText: {
    fontSize: 17,
    color: '#f1f5f9',
    lineHeight: 26,
    fontWeight: '500',
    textAlign: 'center',
  },

  // ── Feedback banner ──
  feedbackBanner: {
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderWidth: 1.5,
    alignItems: 'center',
    gap: 4,
  },
  feedbackLabel: {
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.3,
  },
  feedbackHint: {
    fontSize: 13,
    fontWeight: '600',
    opacity: 0.85,
  },

  // ── Answer buttons ──
  answerButtons: {
    flexDirection: 'row',
    paddingHorizontal: 18,
    paddingBottom: 24,
    paddingTop: 16,
    gap: 12,
  },
  onTopicBtn: {
    flex: 1,
    backgroundColor: '#166534',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#22c55e',
  },
  onTopicBtnText: {
    color: '#22c55e',
    fontSize: 16,
    fontWeight: '800',
  },
  offTopicBtn: {
    flex: 1,
    backgroundColor: '#7f1d1d',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ef4444',
  },
  offTopicBtnText: {
    color: '#ef4444',
    fontSize: 16,
    fontWeight: '800',
  },

  // ── Next button ──
  nextBtn: {
    marginHorizontal: 18,
    marginBottom: 24,
    marginTop: 16,
    backgroundColor: '#3b82f6',
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  nextBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // ── Result ──
  resultOverlay: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    backgroundColor: colors.surface,
  },
  resultCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 12,
  },
  resultEmoji: { fontSize: 56, marginBottom: 8 },
  resultGrade: {
    fontSize: 28,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginBottom: 4,
  },
  resultTopic: {
    fontSize: 15,
    color: colors.muted,
    fontWeight: '600',
    marginBottom: 20,
  },
  resultStats: { width: '100%', gap: 10, marginBottom: 20 },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: colors.surface,
    borderRadius: 10,
  },
  statLabel: { fontSize: 13, color: colors.muted, fontWeight: '600' },
  statValue: { fontSize: 15, color: '#f1f5f9', fontWeight: '800' },
  statValueXP: { fontSize: 17, color: '#f59e0b', fontWeight: '900' },
  badgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#f59e0b22',
    borderWidth: 1,
    borderColor: '#f59e0b66',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 20,
    width: '100%',
    justifyContent: 'center',
  },
  badgeEmoji: { fontSize: 22 },
  badgeText: { fontSize: 14, color: '#f59e0b', fontWeight: '800' },
  resultButtons: { flexDirection: 'row', gap: 12, width: '100%' },
  replayBtn: {
    flex: 1,
    backgroundColor: '#3b82f6',
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  replayBtnText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  exitBtn: {
    flex: 1,
    backgroundColor: colors.surface,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#334155',
  },
  exitBtnText: { color: colors.muted, fontSize: 15, fontWeight: '700' },
});
