import { colors } from '../../theme/colors';
import { layout } from '../../theme/layout';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  textColor: { color: colors.accent },
  scrollViewFlex: { flex: 1 },
  safeArea: {
    ...layout.content,
    flex: 1,
    backgroundColor: colors.background,
  },

  // ── Intro ──
  introContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 28,
    paddingVertical: 20,
  },
  introIconWrap: {
    width: 90,
    height: 90,
    borderRadius: 45,
    backgroundColor: colors.surface,
    borderWidth: 2,
    borderColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 18,
  },
  introIcon: { fontSize: 44 },
  introTitle: {
    fontSize: 32,
    fontWeight: '800',
    color: '#f1f5f9',
    letterSpacing: -0.5,
  },
  introSubtitle: {
    fontSize: 14,
    color: colors.muted,
    marginTop: 4,
    fontWeight: '600',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  introDivider: {
    width: 48,
    height: 3,
    backgroundColor: colors.accent,
    borderRadius: 2,
    marginVertical: 20,
  },
  introDescription: {
    fontSize: 16,
    color: colors.muted,
    textAlign: 'center',
    lineHeight: 24,
    marginBottom: 24,
  },
  introHighlight: { color: colors.accent, fontWeight: '700' },
  introRules: {
    width: '100%',
    backgroundColor: colors.surface,
    borderRadius: 16,
    padding: 18,
    gap: 14,
    marginBottom: 28,
  },
  ruleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  ruleEmoji: { fontSize: 20, width: 28 },
  ruleText: {
    flex: 1,
    fontSize: 14,
    color: '#cbd5e1',
    lineHeight: 20,
    fontWeight: '500',
  },
  startButton: {
    width: '100%',
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.45,
    shadowRadius: 12,
    elevation: 8,
  },
  startButtonText: {
    color: '#fff',
    fontSize: 17,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  backLink: { marginTop: 16, padding: 8 },
  backLinkText: { color: colors.muted, fontSize: 14, fontWeight: '600' },

  // ── Game Header ──
  gameHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 10,
  },
  topicLabel: {
    fontSize: 11,
    color: colors.muted,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
  },
  topicName: {
    fontSize: 17,
    color: '#f1f5f9',
    fontWeight: '800',
    marginTop: 2,
  },
  counterBadge: {
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  counterText: { fontSize: 15, fontWeight: '800', color: colors.accent },

  // ── Progress bar ──
  progressBarBg: {
    height: 4,
    backgroundColor: colors.surface,
    marginHorizontal: 18,
    borderRadius: 2,
    marginBottom: 14,
    overflow: 'hidden',
  },
  progressBarFill: {
    height: '100%',
    backgroundColor: colors.accent,
    borderRadius: 2,
  },

  // ── Game content ──
  gameContent: {
    paddingHorizontal: 18,
    paddingBottom: 20,
    gap: 16,
  },

  // ── Instruction ──
  instructionBanner: {
    backgroundColor: colors.surface,
    borderRadius: 10,
    paddingVertical: 9,
    paddingHorizontal: 14,
    borderLeftWidth: 3,
    borderLeftColor: colors.accent,
  },
  instructionText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  underlineDemo: {
    color: colors.accent,
    textDecorationLine: 'underline',
    fontWeight: '700',
  },

  // ── Sentence card ──
  sentenceCard: {
    backgroundColor: colors.surface,
    borderRadius: 18,
    padding: 22,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 10,
    elevation: 6,
    gap: 14,
  },
  sentenceLabel: {
    fontSize: 10,
    fontWeight: '800',
    color: colors.accent,
    letterSpacing: 2,
    textTransform: 'uppercase',
  },
  sentenceText: {
    fontSize: 19,
    lineHeight: 32,
    color: '#e2e8f0',
    fontWeight: '500',
    flexWrap: 'wrap',
  },
  sentenceTextPart: {
    color: '#e2e8f0',
    fontSize: 19,
    fontWeight: '500',
  },
  swapWord: {
    fontSize: 19,
    fontWeight: '800',
    textDecorationLine: 'underline',
  },
  swapWordEmpty: { color: colors.accent, textDecorationColor: colors.accent },
  swapWordFilled: { color: '#22c55e', textDecorationColor: '#22c55e' },

  // ── Swap chips ──
  swapStatusRow: { gap: 10 },
  swapChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: colors.border,
    gap: 10,
  },
  swapChipFilled: { borderColor: '#22c55e44', backgroundColor: '#14532d22' },
  swapChipOld: {
    fontSize: 14,
    color: colors.muted,
    fontWeight: '600',
    textDecorationLine: 'line-through',
  },
  swapChipOldDone: { color: colors.muted },
  swapChipArrow: { fontSize: 14, color: colors.muted, fontWeight: '700' },
  swapChipNew: { flex: 1, fontSize: 14, fontWeight: '700', color: '#22c55e' },
  swapChipNewEmpty: {
    color: colors.accent,
    fontStyle: 'italic',
    fontWeight: '500',
  },

  hintText: {
    fontSize: 12,
    color: colors.muted,
    textAlign: 'center',
    fontWeight: '600',
  },

  // ── Bottom row ──
  bottomRow: {
    flexDirection: 'row',
    paddingHorizontal: 18,
    paddingBottom: 24,
    paddingTop: 8,
    gap: 10,
  },
  skipBtn: {
    backgroundColor: colors.surface,
    paddingVertical: 16,
    paddingHorizontal: 20,
    borderRadius: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  skipBtnText: { color: colors.muted, fontSize: 14, fontWeight: '700' },
  nextBtn: {
    flex: 1,
    backgroundColor: colors.accent,
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: 'center',
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 6,
  },
  nextBtnDisabled: {
    backgroundColor: colors.surface,
    shadowOpacity: 0,
    elevation: 0,
  },
  nextBtnText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.3,
  },

  // ── Word Bank Panel (inline, replaces Modal) ──
  wordBankPanel: {
    flex: 1,
    backgroundColor: colors.overlay,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    padding: 28,
    paddingBottom: 40,
    gap: 16,
    borderTopWidth: 1,
    borderColor: colors.border,
    marginTop: 8,
  },
  wordBankHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#2d2d4e',
    borderRadius: 2,
    alignSelf: 'center',
    marginBottom: 4,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '800',
    color: '#f1f5f9',
    textAlign: 'center',
  },
  modalSubtitle: {
    fontSize: 14,
    color: colors.muted,
    textAlign: 'center',
    fontWeight: '500',
  },
  modalBoring: {
    color: colors.muted,
    fontStyle: 'italic',
    textDecorationLine: 'line-through',
  },
  wordBankGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    justifyContent: 'center',
  },
  wordChip: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.border,
    minWidth: 100,
    alignItems: 'center',
  },
  wordChipSelected: { backgroundColor: '#3b0764', borderColor: colors.accent },
  wordChipText: { fontSize: 15, color: colors.muted, fontWeight: '600' },
  wordChipTextSelected: { color: '#e9d5ff', fontWeight: '800' },
  confirmBtn: {
    backgroundColor: colors.accent,
    paddingVertical: 15,
    borderRadius: 14,
    alignItems: 'center',
    marginTop: 4,
  },
  confirmBtnDisabled: { backgroundColor: colors.surface },
  confirmBtnText: { color: '#fff', fontSize: 16, fontWeight: '800' },
  cancelLink: { alignItems: 'center', padding: 6 },
  cancelLinkText: { color: colors.muted, fontSize: 14, fontWeight: '600' },

  // ── Result ──
  resultOverlay: {
    flexGrow: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 30,
    backgroundColor: colors.surface,
  },
  resultCard: {
    backgroundColor: colors.surface,
    borderRadius: 24,
    padding: 28,
    width: '100%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.accent,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 20,
    elevation: 12,
  },
  resultEmoji: { fontSize: 56, marginBottom: 8 },
  resultGrade: {
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.5,
    marginBottom: 20,
  },
  resultStats: { width: '100%', gap: 10, marginBottom: 20 },
  statRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 14,
    backgroundColor: colors.surface,
    borderRadius: 10,
  },
  statLabel: { fontSize: 13, color: colors.muted, fontWeight: '600' },
  statValue: { fontSize: 15, color: '#f1f5f9', fontWeight: '800' },
  statValueXP: { fontSize: 17, color: colors.accent, fontWeight: '900' },
  badgeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#a855f722',
    borderWidth: 1,
    borderColor: '#a855f766',
    borderRadius: 10,
    paddingHorizontal: 16,
    paddingVertical: 10,
    marginBottom: 20,
    width: '100%',
    justifyContent: 'center',
  },
  badgeEmoji: { fontSize: 22 },
  badgeText: { fontSize: 14, color: colors.accent, fontWeight: '800' },
  resultButtons: { flexDirection: 'row', gap: 12, width: '100%' },
  replayBtn: {
    flex: 1,
    backgroundColor: colors.accent,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
  },
  replayBtnText: { color: '#fff', fontSize: 15, fontWeight: '800' },
  exitBtn: {
    flex: 1,
    backgroundColor: colors.surface,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  exitBtnText: { color: colors.muted, fontSize: 15, fontWeight: '700' },
});
